In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [25]:
df = pd.read_csv('/Users/purva/Desktop/Data Science Boot Camp/table_crime data_csv.csv', header = 1)

In [26]:
df.head()

,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition)1,Rape (legacy definition)2,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft,Arson3,Unnamed: 13
0,Adams Village,"1,861",0,0,NaN,0,0,0,12,2,10,0,0.0,NaN
1,Addison Town and Village,"2,577",3,0,NaN,0,0,3,24,3,20,1,0.0,NaN
2,Akron Village,"2,846",3,0,NaN,0,0,3,16,1,15,0,0.0,NaN
3,Albany,"97,956",791,8,NaN,30,227,526,"4,090",705,"3,243",142,NaN,NaN
4,Albion Village,"6,388",23,0,NaN,3,4,16,223,53,165,5,NaN,NaN

In [27]:

df.drop(['Rape\n(revised\ndefinition)1','Arson3', 'Unnamed: 13'], axis=1)

,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (legacy definition)2,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft
0,Adams Village,"1,861",0,0,0,0,0,12,2,10,0
1,Addison Town and Village,"2,577",3,0,0,0,3,24,3,20,1
2,Akron Village,"2,846",3,0,0,0,3,16,1,15,0
3,Albany,"97,956",791,8,30,227,526,"4,090",705,"3,243",142
4,Albion Village,"6,388",23,0,3,4,16,223,53,165,5
5,Alfred Village,"4,089",5,0,0,3,2,46,10,36,0
6,Allegany Village,"1,781",3,0,0,0,3,10,0,10,0
7,Amherst Town,"118,296",107,1,7,31,68,"2,118",204,"1,882",32
8,Amityville Village,"9,519",9,0,2,4,3,210,16,188,6
9,Amsterdam,"18,182",30,0,0,12,18,405,99,291,15
10,Arcade Village,"2,053",0,0,0,0,0,39,3,35,1
11,Ardsley Village,"4,523",5,0,0,3,2,33,4,28,1
12,Asharoken Village,658,0,0,0,0,0,2,0,2,0
13,Attica Village,"2,522",2,0,0,0,2,5,0,4,1
14,Auburn,"27,270",96,1,20,22,53,859,132,721,6
15,Avon Village,"3,333",1,0,0,1,0,25,3,20,2
16,Baldwinsville Village,"7,473",5,0,0,1,4,88,10,77,1
17,Ballston Spa Village,"5,418",8,0,0,3,5,94,16,78,0
18,Batavia,"15,374",57,0,7,13,37,559,103,454,2
19,Bath Village,"5,733",15,0,1,3,11,191,32,157,2
20,Bedford Town,"17,627",5,0,0,1,4,156,26,127,3
21,Bethlehem Town,"34,243",13,0,0,3,10,442,50,388,4
22,Binghamton,"46,304",284,3,19,101,161,"2,349",525,"1,767",57
23,Black River,"1,410",0,0,0,0,0,14,2,12,0
24,Blooming Grove Town,"12,001",8,0,1,0,7,99,20,72,7
25,Bolivar Village,"1,022",1,0,0,0,1,4,2,2,0
26,Bolton Town,"2,325",2,0,0,0,2,24,4,20,0
27,Boonville Village,"2,054",1,0,0,0,1,20,6,14,0
28,Brant Town,"2,065",4,0,0,1,3,31,9,20,2
29,Brewster,"2,358",0,0,0,0,0,13,3,10,0
...,...,...,...,...,...,...,...,...,...,...,...
318,Tupper Lake Village,"3,642",3,0,0,0,3,83,22,59,2
319,Tuxedo Park Village,615,0,0,0,0,0,0,0,0,0
320,Ulster Town,"12,195",14,0,3,2,9,437,25,410,2
321,Utica,"61,686",361,7,27,102,225,"2,528",449,"1,997",82
322,Vestal Town,"27,980",16,0,2,6,8,571,39,523,9
323,Walden Village,"6,887",18,1,2,1,14,142,13,124,5
324,Wallkill Town,"27,940",40,0,3,16,21,767,91,650,26
325,Walton Village,"3,012",6,0,1,0,5,68,18,50,0
326,Warsaw Village,"3,453",6,0,1,0,5,78,5,73,0
327,Washingtonville Village,"5,828",2,0,0,1,1,58,5,51,2
328,Waterford Town and Village,"8,392",4,0,0,0,4,59,6,52,1
329,Waterloo Village,"5,175",11,0,0,3,8,194,23,169,2
330,Watertown,"28,179",109,0,12,16,81,"1,165",169,953,43
331,Watervliet,"10,245",26,1,3,11,11,242,58,163,21
332,Watkins Glen Village,"1,862",6,0,0,0,6,92,10,80,2
333,Waverly Village,"4,337",5,0,0,1,4,54,9,41,4
334,Webster Town and Village,"43,777",21,0,2,3,16,469,101,361,7
335,Weedsport Village,"1,797",0,0,0,0,0,25,5,20,0
336,Wellsville Village,"4,574",11,0,1,0,10,164,32,129,3
337,Westhampton Beach Village,"1,732",2,0,0,0,2,44,4,37,3
338,West Seneca Town,"44,821",35,1,1,9,24,896,166,710,20
339,Whitehall Village,"2,604",6,0,0,0,6,62,12,49,1
340,White Plains,"57,559",78,1,3,28,46,"1,232",77,"1,134",21
341,Whitesboro Village,"3,733",4,0,0,0,4,36,14,21,1
342,Whitestown Town,"9,141",0,0,0,0,0,77,13,61,3
343,Woodbury Town,"10,685",3,0,0,2,1,541,9,529,3
344,Woodridge Village,829,7,0,0,0,7,17,8,9,0
345,Woodstock Town,"5,931",2,0,0,0,2,58,13,45,0
346,Yonkers,"199,134","1,036",6,25,390,615,"2,368",470,"1,662",236
347,Yorktown Town,"36,643",15,0,0,2,13,334,45,287,2

In [28]:
df['Property\ncrime']=df['Property\ncrime'].str.replace(',','')
df['Property\ncrime']=df['Property\ncrime'].astype(int)
df['Population'] = (df['Population']).str.replace(',','')
df['Population'] = (df['Population']).astype(int)
df['Robbery'] = (df['Robbery']).str.replace(',','')
df['Robbery'] = (df['Robbery']).astype(int)
df['Larceny-\ntheft'] = (df['Larceny-\ntheft']).str.replace(',','')
df['Larceny-\ntheft'] = (df['Larceny-\ntheft']).astype(int)
df['Burglary'] = (df['Burglary']).str.replace(',','')
df['Burglary'] = (df['Burglary']).astype(int)

In [29]:
df['feature_Murder'] = df['Murder and\nnonnegligent\nmanslaughter']
df.loc[df['feature_Murder'] > 0, 'feature_Murder'] = 1

## Logistic Regression

In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn import linear_model
lr = LogisticRegression(C=1e9)

In [31]:
X= df[['Population','Robbery', 'Property\ncrime', 'Burglary']]
Y = df['feature_Murder']

In [35]:
model1 = lr.fit(X,Y)

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

In [37]:
print('Coefficients')
print(model1.coef_)
print(model1.intercept_)
pred_y_sklearn = lr.predict(X)

print('\n Accuracy')
print(pd.crosstab(pred_y_sklearn, Y))

print('\n Percentage accuracy')
print(lr.score(X, Y))

Coefficients
[[ 2.52576912e-05  1.83733090e-02 -1.10435520e-03  9.73278936e-03]]
[-2.49793057]

 Accuracy
feature_Murder    0   1
row_0
0               293  30
1                 6  19

 Percentage accuracy
0.896551724137931

## Ridge Regression

In [47]:
rr = linear_model.Ridge(alpha = 10, fit_intercept = False)
model2 = rr.fit(X,Y)
print('Coefficients')
print(model2.coef_)
print(model2.intercept_)
pred_y_sklearn = rr.predict(X)

##print('\n Accuracy')
##print(pd.crosstab(pred_y_sklearn, Y))

print('\n Percentage accuracy')
print(rr.score(X, Y))

Coefficients
[ 7.52410488e-06 -3.55525250e-03 -1.60242087e-04  1.73197092e-03]
0.0

 Percentage accuracy
0.24078639344075892

## Lasso Regression

In [54]:
lass = linear_model.Lasso(alpha = 0.40)
model3 = lass.fit(X,Y)
print('Coefficients')
print(model3.coef_)
print(model3.intercept_)
pred_y_sklearn = lass.predict(X)

##print('\n Accuracy')
##print(pd.crosstab(pred_y_sklearn, Y))

print('\n Percentage accuracy')
print(lass.score(X, Y))

Coefficients
[ 5.09559540e-07 -1.80108171e-03  1.71151359e-04  4.17075728e-04]
0.0661331353878811

 Percentage accuracy
0.2136440474481144

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)